// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swjrdhxljjlnvbzetaqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3anJkaHhsampsbnZiemV0YXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODI4MDIsImV4cCI6MjA1ODc1ODgwMn0.kb-FWv6FSH5R16QL3jOUqItxSZpT6QdelOFujgp-96o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);